name: Copy Parse Markdown and Generate JSON from Source Repo

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository name'
        required: false
        default: 'DmitryRyumin/NewEraAI-Papers'
      source_file_path:
        description: 'Path to the file in the source repository'
        required: false
        default: 'code/markdown_to_json_parser.py'
  schedule:
    - cron: '30 23 * * *'

jobs:
  copy-code:
    runs-on: ubuntu-latest

    env:
      CODE_DIR: '${{ github.workspace }}/code'
      SOURCE_FILE_PATH: '${{ CODE_DIR }}/markdown_to_json_parser_new.py'

    steps:
      - name: Create code directory
        run: mkdir -p "${{ CODE_DIR }}"

      - name: Download source file
        run: |
          source_url="https://raw.githubusercontent.com/${{ github.event.inputs.source_repo }}/main/${{ github.event.inputs.source_file_path }}"
          curl -o "${{ env.SOURCE_FILE_PATH }}" "$source_url"
          echo "File downloaded successfully"

      - name: Display content of the downloaded source file
        run: cat "${{ env.SOURCE_FILE_PATH }}"
