name: Copy Parse Markdown and Generate JSON from Source Repo

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository name'
        required: false
        default: 'DmitryRyumin/NewEraAI-Papers'
      source_file_path:
        description: 'Path to the file in the source repository'
        required: false
        default: 'code/markdown_to_json_parser.py'
      destination_file_path:
        description: 'Path to the destination file in the target repository'
        required: false
        default: 'code/markdown_to_json_parser.py'
  schedule:
    - cron: '30 23 * * *'

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: main

      - name: Check if file exists and is unchanged
        run: |
          source_path="${{ github.workspace }}/${{ github.event.inputs.source_file_path }}"
          destination_path="${{ github.workspace }}/${{ github.event.inputs.destination_file_path }}"

          echo "Content of destination file:"
          cat "$destination_path"
          echo "Content of source file:"
          cat "$source_path"
        working-directory: .
