name: Copy Parse Markdown and Generate JSON from Source Repo

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository name'
        required: false
        default: 'DmitryRyumin/NewEraAI-Papers'
      source_file_path:
        description: 'Path to the file in the source repository'
        required: false
        default: 'code/markdown_to_json_parser.py'
      destination_file_path:
        description: 'Path to the destination file in the target repository'
        required: false
        default: 'code/markdown_to_json_parser.py'
  schedule:
    - cron: '30 23 * * *'

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Display content of source file from source repository
        run: |
          source_path="${{ github.workspace }}/${{ github.event.inputs.source_file_path }}"
          echo "Content of source file from source repository:"
          cat "$source_path"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: DmitryRyumin/WACV-2024-Papers
          ref: main

      - name: Display content of destination file from target repository
        run: |
          destination_path="${{ github.workspace }}/${{ github.event.inputs.destination_file_path }}"
          echo "Content of destination file from target repository:"
          cat "$destination_path"
