name: Copy Parse Markdown and Generate JSON from Source Repo

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository name'
        required: false
        default: 'DmitryRyumin/NewEraAI-Papers'
      source_file_path:
        description: 'Path to the file in the source repository'
        required: false
        default: 'code/markdown_to_json_parser.py'
      destination_file_path:
        description: 'Path to the destination file in the target repository'
        required: false
        default: 'code/markdown_to_json_parser.py'
  schedule:
    - cron: '30 23 * * *'

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: main

      - name: Check if file exists and is unchanged
        run: |
          destination_path="${{ github.event.inputs.destination_file_path }}"
          source_path="${{ github.workspace }}/${{ github.event.inputs.source_file_path }}"

          if [ -f "$destination_path" ]; then
            if diff "$destination_path" "$source_path"; then
              echo "File exists and is unchanged, no need to copy."
              exit 0
            else
              echo "File exists but is different. Here is the diff:"
              diff "$destination_path" "$source_path"
              echo "Copying ..."
            fi
          else
            echo "File does not exist, copying ..."
          fi

          echo "Content of destination file:"
          cat "$destination_path"
          echo "Content of source file:"
          cat "$source_path"
        working-directory: .

      # - name: Copy file
      #   run: |
      #     mkdir -p $(dirname "${{ github.event.inputs.destination_file_path }}")
      #     cp "${{ github.workspace }}/${{ github.event.inputs.source_file_path }}" "${{ github.event.inputs.destination_file_path }}"
      #   working-directory: .

      # - name: Auto commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: 'Copy Parse Markdown and Generate JSON from Source Repo'
      #   env:
      #     PAPER_TOKEN: ${{ secrets.PAPER_TOKEN }}
