name: Parse Markdown and Generate JSON

on:
  push:
    branches:
      - main

jobs:
  parse_markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
          node-version: '16'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 markdown2 prettytable PyGithub flake8

      - name: Run Flake8 (Linting)
        run: flake8 code/

      - name: Run Markdown Parser
        id: parse
        run: python code/markdown_to_json_parser.py
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Upload JSON files
        uses: actions/upload-artifact@v2
        with:
          name: json_data
          path: ${{ github.workspace }}/json_data

      - name: Set output status
        if: steps.parse.outcome == 'success'
        run: echo "status=success" >> $GITHUB_ENV
      - name: Set output status (failure)
        if: steps.parse.outcome == 'failure'
        run: echo "status=failure" >> $GITHUB_ENV
