name: Parse Markdown and Generate JSON

on:
  push:
    branches:
      - main

jobs:
  parse_markdown:
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      # Step: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 markdown2 prettytable flake8

      # Step: Run Flake8 for code style checking
      - name: Run Flake8 (Linting)
        run: flake8 code/

      # Step: Run the Markdown parser script
      - name: Run Markdown Parser
        id: parse
        run: python code/markdown_to_json_parser.py
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      # Step: Set output status based on the script result
      - name: Set output status
        if: steps.parse.outcome == 'success'
        run: echo "status=success" >> $GITHUB_ENV
      - name: Set output status (failure)
        if: steps.parse.outcome == 'failure'
        run: echo "status=failure" >> $GITHUB_ENV
