name: Sync Hugging Face App

on:
  workflow_dispatch:

jobs:
  sync-hf:
    runs-on: ubuntu-latest

    env:
      HF_USERNAME: 'DmitryRyumin'
      HF_REPO: 'NewEraAI-Papers'
      LOCAL_DIR: 'NewEraAI-Papers'
      TOKEN: '${{ secrets.HUGGINGFACE_TOKEN }}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Set REMOTE_URL
        run: |
          echo "REMOTE_URL=https://${{ env.HF_USERNAME }}:${{ secrets.HUGGINGFACE_TOKEN }}@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_REPO }}'" >> $GITHUB_ENV

      - name: Clone Hugging Face Repository
        run: |
          GIT_LFS_SKIP_SMUDGE=1 git clone --quiet --branch=main --single-branch --depth=1 "$REMOTE_URL" huggingface-repo

      - name: Display working code directory Hugging Face
        run: |
          ls -al "${{ github.workspace }}/${{ env.LOCAL_DIR }}"
