name: Sync Hugging Face App

on:
  workflow_dispatch:

jobs:
  sync-hf:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      HF_USERNAME: 'DmitryRyumin'
      HF_REPO: 'NewEraAI-Papers'
      LOCAL_DIR: 'NewEraAI-Papers'
      HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      JSON_DATA_PATH: 'json_data/2024/WACV'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: |
          if [ ! -x "$(command -v git-lfs)" ]; then
            echo "Git LFS is not installed. Installing ..."
            sudo apt-get install git-lfs
          fi
          git lfs install

      - name: Set REMOTE_URL
        run: |
          echo "REMOTE_URL=https://${{ env.HF_USERNAME }}:${{ env.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_REPO }}" >> $GITHUB_ENV

      - name: Clone Hugging Face Repository
        run: |
          GIT_LFS_SKIP_SMUDGE=1 git clone --quiet --branch=main --single-branch --depth=1 "$REMOTE_URL" "${{ env.LOCAL_DIR }}"
        continue-on-error: true

      - name: Display cloned directory contents
        run: |
          ls -al "${{ github.workspace }}/${{ env.LOCAL_DIR }}/${{ env.JSON_DATA_PATH }}"

      - name: Set output status
        run: |
          if [ $? -eq 0 ]; then
            echo "status=success" >> $GITHUB_ENV
          else
            echo "status=failure" >> $GITHUB_ENV
          fi
